/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorisedRouteImport } from './routes/unauthorised'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminVerificationsRouteImport } from './routes/admin.verifications'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminRegulatoryRouteImport } from './routes/admin.regulatory'
import { Route as AdminFraudRouteImport } from './routes/admin.fraud'
import { Route as AdminEnforcementRouteImport } from './routes/admin.enforcement'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminAgentsRouteImport } from './routes/admin.agents'
import { Route as ApiAuthSignoutAllDevicesRouteImport } from './routes/api.auth.signout-all-devices'

const UnauthorisedRoute = UnauthorisedRouteImport.update({
  id: '/unauthorised',
  path: '/unauthorised',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerificationsRoute = AdminVerificationsRouteImport.update({
  id: '/admin/verifications',
  path: '/admin/verifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/admin/reviews',
  path: '/admin/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRegulatoryRoute = AdminRegulatoryRouteImport.update({
  id: '/admin/regulatory',
  path: '/admin/regulatory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFraudRoute = AdminFraudRouteImport.update({
  id: '/admin/fraud',
  path: '/admin/fraud',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEnforcementRoute = AdminEnforcementRouteImport.update({
  id: '/admin/enforcement',
  path: '/admin/enforcement',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAgentsRoute = AdminAgentsRouteImport.update({
  id: '/admin/agents',
  path: '/admin/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignoutAllDevicesRoute =
  ApiAuthSignoutAllDevicesRouteImport.update({
    id: '/api/auth/signout-all-devices',
    path: '/api/auth/signout-all-devices',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorised': typeof UnauthorisedRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/enforcement': typeof AdminEnforcementRoute
  '/admin/fraud': typeof AdminFraudRoute
  '/admin/regulatory': typeof AdminRegulatoryRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/signout-all-devices': typeof ApiAuthSignoutAllDevicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorised': typeof UnauthorisedRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/enforcement': typeof AdminEnforcementRoute
  '/admin/fraud': typeof AdminFraudRoute
  '/admin/regulatory': typeof AdminRegulatoryRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/admin': typeof AdminIndexRoute
  '/api/auth/signout-all-devices': typeof ApiAuthSignoutAllDevicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorised': typeof UnauthorisedRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/enforcement': typeof AdminEnforcementRoute
  '/admin/fraud': typeof AdminFraudRoute
  '/admin/regulatory': typeof AdminRegulatoryRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/signout-all-devices': typeof ApiAuthSignoutAllDevicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/unauthorised'
    | '/admin/agents'
    | '/admin/content'
    | '/admin/enforcement'
    | '/admin/fraud'
    | '/admin/regulatory'
    | '/admin/reviews'
    | '/admin/verifications'
    | '/admin/'
    | '/api/auth/signout-all-devices'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/unauthorised'
    | '/admin/agents'
    | '/admin/content'
    | '/admin/enforcement'
    | '/admin/fraud'
    | '/admin/regulatory'
    | '/admin/reviews'
    | '/admin/verifications'
    | '/admin'
    | '/api/auth/signout-all-devices'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/unauthorised'
    | '/admin/agents'
    | '/admin/content'
    | '/admin/enforcement'
    | '/admin/fraud'
    | '/admin/regulatory'
    | '/admin/reviews'
    | '/admin/verifications'
    | '/admin/'
    | '/api/auth/signout-all-devices'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  UnauthorisedRoute: typeof UnauthorisedRoute
  AdminAgentsRoute: typeof AdminAgentsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminEnforcementRoute: typeof AdminEnforcementRoute
  AdminFraudRoute: typeof AdminFraudRoute
  AdminRegulatoryRoute: typeof AdminRegulatoryRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminVerificationsRoute: typeof AdminVerificationsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiAuthSignoutAllDevicesRoute: typeof ApiAuthSignoutAllDevicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorised': {
      id: '/unauthorised'
      path: '/unauthorised'
      fullPath: '/unauthorised'
      preLoaderRoute: typeof UnauthorisedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verifications': {
      id: '/admin/verifications'
      path: '/admin/verifications'
      fullPath: '/admin/verifications'
      preLoaderRoute: typeof AdminVerificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/regulatory': {
      id: '/admin/regulatory'
      path: '/admin/regulatory'
      fullPath: '/admin/regulatory'
      preLoaderRoute: typeof AdminRegulatoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/fraud': {
      id: '/admin/fraud'
      path: '/admin/fraud'
      fullPath: '/admin/fraud'
      preLoaderRoute: typeof AdminFraudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/enforcement': {
      id: '/admin/enforcement'
      path: '/admin/enforcement'
      fullPath: '/admin/enforcement'
      preLoaderRoute: typeof AdminEnforcementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/agents': {
      id: '/admin/agents'
      path: '/admin/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AdminAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signout-all-devices': {
      id: '/api/auth/signout-all-devices'
      path: '/api/auth/signout-all-devices'
      fullPath: '/api/auth/signout-all-devices'
      preLoaderRoute: typeof ApiAuthSignoutAllDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  UnauthorisedRoute: UnauthorisedRoute,
  AdminAgentsRoute: AdminAgentsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminEnforcementRoute: AdminEnforcementRoute,
  AdminFraudRoute: AdminFraudRoute,
  AdminRegulatoryRoute: AdminRegulatoryRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminVerificationsRoute: AdminVerificationsRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiAuthSignoutAllDevicesRoute: ApiAuthSignoutAllDevicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
